=== chuttmateo/test-automation-course/zoo-maven/src/main/resources/xml/visitor.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="visitorType">
        <xs:all>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long"/>
    </xs:complexType>

    <xs:complexType name="visitorsType">
        <xs:sequence>
            <xs:element name="visitor" type="visitorType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="visitors" type="visitorsType"/>

</xs:schema>

=== chuttmateo/test-automation-course/zoo-maven/src/main/resources/xml/visitor.xml
<visitors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="visitor.xsd">
    <visitor id="1">
        <firstName>Diego</firstName>
        <lastName>Smith</lastName>
    </visitor>
    <visitor id="2">
        <firstName>Juan</firstName>
        <lastName>Ivanov</lastName>
    </visitor>
    <visitor id="3">
        <firstName>Paul</firstName>
        <lastName>Doe</lastName>
    </visitor>
    <visitor id="4">
        <firstName>Mateo</firstName>
        <lastName>Audisio</lastName>
    </visitor>
</visitors>
